export const POINT_REASONS = {
  FOCUS_SESSION_COMPLETE: 'FOCUS_SESSION_COMPLETE',
  HABIT_COMPLETE: 'HABIT_COMPLETE',
  EVENT_REWARD: 'EVENT_REWARD',
  ETC: 'ETC',
};

export const POINT_REASON_VALUES = Object.values(POINT_REASONS);
